[package]
name = "lucide-slint"
description = "Implementation of the lucide icon library for Slint."
version = "0.2.0"
edition = "2024"
license = "MIT AND ISC"
include = ["lib.slint", "src/lib.rs"]
repository = "https://github.com/cnlancehu/lucide-slint"
