[package]
name = "lucide-slint"
description = "Use lucide icons in Slint applications with ease!"
version = "0.562.1"
edition = "2024"
license = "MIT AND ISC"
include = ["lib.slint", "src/lib.rs"]
repository = "https://github.com/cnlancehu/lucide-slint"
